### ISSUE TITLE
[SuperVillain UI: UnitFrames v20161018222025] HP Bar above the mob is bugged :(

### ISSUE THREAD

**Issue by Bardaf01** [failcoder/supervillain-ui#2]
Hello !

First, thanks for this wonderful add-on ! Next, I'm sorry to tell you about an issue... 
**In fact, the _HP Bar_ above the mob is _bugged_. :(** 

Please see the picture : 

![wowscrnshot_unitframebug](https://cloud.githubusercontent.com/assets/22980565/19599678/39bfb660-97a2-11e6-9e32-01a81516712f.jpg)

Thanks a lot !
Best regards.

**Comment by djchsu11** [comment]
Workaround from discord, until it's fixed:
joev - Last Thursday at 1:06 PM
Ok. in Supervillain settings: Go to: Unitframes. Uncheck "disable blizzard" and enable "Smooth Bars"
That'll make the nameplates work (counter intuitive I know but it's the only workaround which works in the release version)

**Comment by Bardaf01** [comment]
> Workaround from discord, until it's fixed:
> joev - Last Thursday at 1:06 PM
> _**Ok. in Supervillain settings: Go to: Unitframes. Uncheck "disable blizzard" and enable "Smooth Bars"**_
> **_That'll make the nameplates work (counter intuitive I know but it's the only workaround which works in the release version)_**

Ok, thanks ! :)
It's working now !

**Comment by joev** [comment]
@Bardaf01 This repo version is actually fully working with new nameplates (some configurations not yet available but working nonetheless) so I'm closing this and you will get a properly updated version on next release (@failcoder is working on it at the moment)
